gmail_user: "adityatomar0025@gmail.com"
gmail_app_password: "zqyt szpi exiy vdul"
alert_recipient: "adityatomar381@gmail.com"
slack_webhook_url: "https://hooks.slack.com/services/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"